# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/clement/Desktop/eagleemu/eagleemu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/clement/Desktop/eagleemu/eagleemu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clement/Desktop/eagleemu/eagleemu/CMakeFiles /home/clement/Desktop/eagleemu/eagleemu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clement/Desktop/eagleemu/eagleemu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eagleemu

# Build rule for target.
eagleemu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eagleemu
.PHONY : eagleemu

# fast build rule for target.
eagleemu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/build
.PHONY : eagleemu/fast

8255.o: 8255.c.o
.PHONY : 8255.o

# target to build an object file
8255.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/8255.c.o
.PHONY : 8255.c.o

8255.i: 8255.c.i
.PHONY : 8255.i

# target to preprocess a source file
8255.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/8255.c.i
.PHONY : 8255.c.i

8255.s: 8255.c.s
.PHONY : 8255.s

# target to generate assembly for a file
8255.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/8255.c.s
.PHONY : 8255.c.s

cpu.o: cpu.c.o
.PHONY : cpu.o

# target to build an object file
cpu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/cpu.c.o
.PHONY : cpu.c.o

cpu.i: cpu.c.i
.PHONY : cpu.i

# target to preprocess a source file
cpu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/cpu.c.i
.PHONY : cpu.c.i

cpu.s: cpu.c.s
.PHONY : cpu.s

# target to generate assembly for a file
cpu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/cpu.c.s
.PHONY : cpu.c.s

gfx.o: gfx.c.o
.PHONY : gfx.o

# target to build an object file
gfx.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/gfx.c.o
.PHONY : gfx.c.o

gfx.i: gfx.c.i
.PHONY : gfx.i

# target to preprocess a source file
gfx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/gfx.c.i
.PHONY : gfx.c.i

gfx.s: gfx.c.s
.PHONY : gfx.s

# target to generate assembly for a file
gfx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/gfx.c.s
.PHONY : gfx.c.s

keyb.o: keyb.c.o
.PHONY : keyb.o

# target to build an object file
keyb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/keyb.c.o
.PHONY : keyb.c.o

keyb.i: keyb.c.i
.PHONY : keyb.i

# target to preprocess a source file
keyb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/keyb.c.i
.PHONY : keyb.c.i

keyb.s: keyb.c.s
.PHONY : keyb.s

# target to generate assembly for a file
keyb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/keyb.c.s
.PHONY : keyb.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/main.c.s
.PHONY : main.c.s

saa1099_ext.o: saa1099_ext.c.o
.PHONY : saa1099_ext.o

# target to build an object file
saa1099_ext.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/saa1099_ext.c.o
.PHONY : saa1099_ext.c.o

saa1099_ext.i: saa1099_ext.c.i
.PHONY : saa1099_ext.i

# target to preprocess a source file
saa1099_ext.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/saa1099_ext.c.i
.PHONY : saa1099_ext.c.i

saa1099_ext.s: saa1099_ext.c.s
.PHONY : saa1099_ext.s

# target to generate assembly for a file
saa1099_ext.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/saa1099_ext.c.s
.PHONY : saa1099_ext.c.s

sd.o: sd.c.o
.PHONY : sd.o

# target to build an object file
sd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/sd.c.o
.PHONY : sd.c.o

sd.i: sd.c.i
.PHONY : sd.i

# target to preprocess a source file
sd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/sd.c.i
.PHONY : sd.c.i

sd.s: sd.c.s
.PHONY : sd.s

# target to generate assembly for a file
sd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/sd.c.s
.PHONY : sd.c.s

serial.o: serial.c.o
.PHONY : serial.o

# target to build an object file
serial.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/serial.c.o
.PHONY : serial.c.o

serial.i: serial.c.i
.PHONY : serial.i

# target to preprocess a source file
serial.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/serial.c.i
.PHONY : serial.c.i

serial.s: serial.c.s
.PHONY : serial.s

# target to generate assembly for a file
serial.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eagleemu.dir/build.make CMakeFiles/eagleemu.dir/serial.c.s
.PHONY : serial.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... eagleemu"
	@echo "... 8255.o"
	@echo "... 8255.i"
	@echo "... 8255.s"
	@echo "... cpu.o"
	@echo "... cpu.i"
	@echo "... cpu.s"
	@echo "... gfx.o"
	@echo "... gfx.i"
	@echo "... gfx.s"
	@echo "... keyb.o"
	@echo "... keyb.i"
	@echo "... keyb.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... saa1099_ext.o"
	@echo "... saa1099_ext.i"
	@echo "... saa1099_ext.s"
	@echo "... sd.o"
	@echo "... sd.i"
	@echo "... sd.s"
	@echo "... serial.o"
	@echo "... serial.i"
	@echo "... serial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

